// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protos/data/credentials.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Metainfo      string                 `protobuf:"bytes,4,opt,name=metainfo,proto3" json:"metainfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credentials) GetMetainfo() string {
	if x != nil {
		return x.Metainfo
	}
	return ""
}

type StoreCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCredentialsRequest) Reset() {
	*x = StoreCredentialsRequest{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCredentialsRequest) ProtoMessage() {}

func (x *StoreCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCredentialsRequest.ProtoReflect.Descriptor instead.
func (*StoreCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *StoreCredentialsRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type StoreCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCredentialsResponse) Reset() {
	*x = StoreCredentialsResponse{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCredentialsResponse) ProtoMessage() {}

func (x *StoreCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCredentialsResponse.ProtoReflect.Descriptor instead.
func (*StoreCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *StoreCredentialsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsRequest) Reset() {
	*x = GetCredentialsRequest{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsRequest) ProtoMessage() {}

func (x *GetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{4}
}

func (x *GetCredentialsResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *GetCredentialsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EditCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCredentialsRequest) Reset() {
	*x = EditCredentialsRequest{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCredentialsRequest) ProtoMessage() {}

func (x *EditCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCredentialsRequest.ProtoReflect.Descriptor instead.
func (*EditCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{5}
}

func (x *EditCredentialsRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type EditCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCredentialsResponse) Reset() {
	*x = EditCredentialsResponse{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCredentialsResponse) ProtoMessage() {}

func (x *EditCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCredentialsResponse.ProtoReflect.Descriptor instead.
func (*EditCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{6}
}

func (x *EditCredentialsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialsRequest) Reset() {
	*x = DeleteCredentialsRequest{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialsRequest) ProtoMessage() {}

func (x *DeleteCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialsRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialsResponse) Reset() {
	*x = DeleteCredentialsResponse{}
	mi := &file_internal_protos_data_credentials_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialsResponse) ProtoMessage() {}

func (x *DeleteCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_data_credentials_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialsResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_data_credentials_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCredentialsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_protos_data_credentials_proto protoreflect.FileDescriptor

const file_internal_protos_data_credentials_proto_rawDesc = "" +
	"\n" +
	"&internal/protos/data/credentials.proto\x12\x04data\"o\n" +
	"\vCredentials\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bmetainfo\x18\x04 \x01(\tR\bmetainfo\"N\n" +
	"\x17StoreCredentialsRequest\x123\n" +
	"\vcredentials\x18\x01 \x01(\v2\x11.data.CredentialsR\vcredentials\"0\n" +
	"\x18StoreCredentialsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"+\n" +
	"\x15GetCredentialsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"c\n" +
	"\x16GetCredentialsResponse\x123\n" +
	"\vcredentials\x18\x01 \x01(\v2\x11.data.CredentialsR\vcredentials\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x16EditCredentialsRequest\x123\n" +
	"\vcredentials\x18\x01 \x01(\v2\x11.data.CredentialsR\vcredentials\"-\n" +
	"\x17EditCredentialsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x18DeleteCredentialsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x19DeleteCredentialsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xd6\x02\n" +
	"\x0eDataController\x12Q\n" +
	"\x10StoreCredentials\x12\x1d.data.StoreCredentialsRequest\x1a\x1e.data.StoreCredentialsResponse\x12K\n" +
	"\x0eGetCredentials\x12\x1b.data.GetCredentialsRequest\x1a\x1c.data.GetCredentialsResponse\x12N\n" +
	"\x0fEditCredentials\x12\x1c.data.EditCredentialsRequest\x1a\x1d.data.EditCredentialsResponse\x12T\n" +
	"\x11DeleteCredentials\x12\x1e.data.DeleteCredentialsRequest\x1a\x1f.data.DeleteCredentialsResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_internal_protos_data_credentials_proto_rawDescOnce sync.Once
	file_internal_protos_data_credentials_proto_rawDescData []byte
)

func file_internal_protos_data_credentials_proto_rawDescGZIP() []byte {
	file_internal_protos_data_credentials_proto_rawDescOnce.Do(func() {
		file_internal_protos_data_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_data_credentials_proto_rawDesc), len(file_internal_protos_data_credentials_proto_rawDesc)))
	})
	return file_internal_protos_data_credentials_proto_rawDescData
}

var file_internal_protos_data_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_protos_data_credentials_proto_goTypes = []any{
	(*Credentials)(nil),               // 0: data.Credentials
	(*StoreCredentialsRequest)(nil),   // 1: data.StoreCredentialsRequest
	(*StoreCredentialsResponse)(nil),  // 2: data.StoreCredentialsResponse
	(*GetCredentialsRequest)(nil),     // 3: data.GetCredentialsRequest
	(*GetCredentialsResponse)(nil),    // 4: data.GetCredentialsResponse
	(*EditCredentialsRequest)(nil),    // 5: data.EditCredentialsRequest
	(*EditCredentialsResponse)(nil),   // 6: data.EditCredentialsResponse
	(*DeleteCredentialsRequest)(nil),  // 7: data.DeleteCredentialsRequest
	(*DeleteCredentialsResponse)(nil), // 8: data.DeleteCredentialsResponse
}
var file_internal_protos_data_credentials_proto_depIdxs = []int32{
	0, // 0: data.StoreCredentialsRequest.credentials:type_name -> data.Credentials
	0, // 1: data.GetCredentialsResponse.credentials:type_name -> data.Credentials
	0, // 2: data.EditCredentialsRequest.credentials:type_name -> data.Credentials
	1, // 3: data.DataController.StoreCredentials:input_type -> data.StoreCredentialsRequest
	3, // 4: data.DataController.GetCredentials:input_type -> data.GetCredentialsRequest
	5, // 5: data.DataController.EditCredentials:input_type -> data.EditCredentialsRequest
	7, // 6: data.DataController.DeleteCredentials:input_type -> data.DeleteCredentialsRequest
	2, // 7: data.DataController.StoreCredentials:output_type -> data.StoreCredentialsResponse
	4, // 8: data.DataController.GetCredentials:output_type -> data.GetCredentialsResponse
	6, // 9: data.DataController.EditCredentials:output_type -> data.EditCredentialsResponse
	8, // 10: data.DataController.DeleteCredentials:output_type -> data.DeleteCredentialsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protos_data_credentials_proto_init() }
func file_internal_protos_data_credentials_proto_init() {
	if File_internal_protos_data_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_data_credentials_proto_rawDesc), len(file_internal_protos_data_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_data_credentials_proto_goTypes,
		DependencyIndexes: file_internal_protos_data_credentials_proto_depIdxs,
		MessageInfos:      file_internal_protos_data_credentials_proto_msgTypes,
	}.Build()
	File_internal_protos_data_credentials_proto = out.File
	file_internal_protos_data_credentials_proto_goTypes = nil
	file_internal_protos_data_credentials_proto_depIdxs = nil
}
