// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protos/items/items.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ITEM_TYPE_EMPTY       ItemType = 0
	ItemType_ITEM_TYPE_UNSPECIFIED ItemType = 1
	ItemType_ITEM_TYPE_CREDENTIALS ItemType = 2
	ItemType_ITEM_TYPE_TEXT        ItemType = 3
	ItemType_ITEM_TYPE_BINARY      ItemType = 4
	ItemType_ITEM_TYPE_CARD        ItemType = 5
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_EMPTY",
		1: "ITEM_TYPE_UNSPECIFIED",
		2: "ITEM_TYPE_CREDENTIALS",
		3: "ITEM_TYPE_TEXT",
		4: "ITEM_TYPE_BINARY",
		5: "ITEM_TYPE_CARD",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_EMPTY":       0,
		"ITEM_TYPE_UNSPECIFIED": 1,
		"ITEM_TYPE_CREDENTIALS": 2,
		"ITEM_TYPE_TEXT":        3,
		"ITEM_TYPE_BINARY":      4,
		"ITEM_TYPE_CARD":        5,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_items_items_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_internal_protos_items_items_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{0}
}

type EncryptedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserLogin     string                 `protobuf:"bytes,2,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          ItemType               `protobuf:"varint,4,opt,name=type,proto3,enum=items.ItemType" json:"type,omitempty"`
	EncryptedData *EncryptedData         `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedItem) Reset() {
	*x = EncryptedItem{}
	mi := &file_internal_protos_items_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedItem) ProtoMessage() {}

func (x *EncryptedItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedItem.ProtoReflect.Descriptor instead.
func (*EncryptedItem) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedItem) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *EncryptedItem) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *EncryptedItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncryptedItem) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_EMPTY
}

func (x *EncryptedItem) GetEncryptedData() *EncryptedData {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *EncryptedItem) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *EncryptedItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EncryptedItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EncryptedData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedContent string                 `protobuf:"bytes,1,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"`
	Nonce            string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_internal_protos_items_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedData) GetEncryptedContent() string {
	if x != nil {
		return x.EncryptedContent
	}
	return ""
}

func (x *EncryptedData) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *EncryptedItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_internal_protos_items_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemRequest) GetItem() *EncryptedItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_internal_protos_items_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLogin     string                 `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=items.ItemType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserItemsRequest) Reset() {
	*x = GetUserItemsRequest{}
	mi := &file_internal_protos_items_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserItemsRequest) ProtoMessage() {}

func (x *GetUserItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserItemsRequest.ProtoReflect.Descriptor instead.
func (*GetUserItemsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserItemsRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *GetUserItemsRequest) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_EMPTY
}

type GetUserItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EncryptedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserItemsResponse) Reset() {
	*x = GetUserItemsResponse{}
	mi := &file_internal_protos_items_items_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserItemsResponse) ProtoMessage() {}

func (x *GetUserItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserItemsResponse.ProtoReflect.Descriptor instead.
func (*GetUserItemsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserItemsResponse) GetItems() []*EncryptedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type EditItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *EncryptedItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditItemRequest) Reset() {
	*x = EditItemRequest{}
	mi := &file_internal_protos_items_items_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditItemRequest) ProtoMessage() {}

func (x *EditItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditItemRequest.ProtoReflect.Descriptor instead.
func (*EditItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{6}
}

func (x *EditItemRequest) GetItem() *EncryptedItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type EditItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditItemResponse) Reset() {
	*x = EditItemResponse{}
	mi := &file_internal_protos_items_items_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditItemResponse) ProtoMessage() {}

func (x *EditItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditItemResponse.ProtoReflect.Descriptor instead.
func (*EditItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{7}
}

func (x *EditItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLogin     string                 `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	ItemId        []byte                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_internal_protos_items_items_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *DeleteItemRequest) GetItemId() []byte {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_internal_protos_items_items_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TypesCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLogin     string                 `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypesCountsRequest) Reset() {
	*x = TypesCountsRequest{}
	mi := &file_internal_protos_items_items_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypesCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypesCountsRequest) ProtoMessage() {}

func (x *TypesCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypesCountsRequest.ProtoReflect.Descriptor instead.
func (*TypesCountsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{10}
}

func (x *TypesCountsRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

type TypesCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         map[string]int32       `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypesCountsResponse) Reset() {
	*x = TypesCountsResponse{}
	mi := &file_internal_protos_items_items_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypesCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypesCountsResponse) ProtoMessage() {}

func (x *TypesCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_items_items_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypesCountsResponse.ProtoReflect.Descriptor instead.
func (*TypesCountsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_items_items_proto_rawDescGZIP(), []int{11}
}

func (x *TypesCountsResponse) GetTypes() map[string]int32 {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_internal_protos_items_items_proto protoreflect.FileDescriptor

const file_internal_protos_items_items_proto_rawDesc = "" +
	"\n" +
	"!internal/protos/items/items.proto\x12\x05items\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x03\n" +
	"\rEncryptedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1d\n" +
	"\n" +
	"user_login\x18\x02 \x01(\tR\tuserLogin\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.items.ItemTypeR\x04type\x12;\n" +
	"\x0eencrypted_data\x18\x05 \x01(\v2\x14.items.EncryptedDataR\rencryptedData\x122\n" +
	"\x04meta\x18\x06 \x03(\v2\x1e.items.EncryptedItem.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\rEncryptedData\x12+\n" +
	"\x11encrypted_content\x18\x01 \x01(\tR\x10encryptedContent\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\":\n" +
	"\x0eAddItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.items.EncryptedItemR\x04item\"+\n" +
	"\x0fAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x13GetUserItemsRequest\x12\x1d\n" +
	"\n" +
	"user_login\x18\x01 \x01(\tR\tuserLogin\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.items.ItemTypeR\x04type\"B\n" +
	"\x14GetUserItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.items.EncryptedItemR\x05items\";\n" +
	"\x0fEditItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.items.EncryptedItemR\x04item\",\n" +
	"\x10EditItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x11DeleteItemRequest\x12\x1d\n" +
	"\n" +
	"user_login\x18\x01 \x01(\tR\tuserLogin\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\fR\x06itemId\".\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12TypesCountsRequest\x12\x1d\n" +
	"\n" +
	"user_login\x18\x01 \x01(\tR\tuserLogin\"\x8c\x01\n" +
	"\x13TypesCountsResponse\x12;\n" +
	"\x05types\x18\x01 \x03(\v2%.items.TypesCountsResponse.TypesEntryR\x05types\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\x93\x01\n" +
	"\bItemType\x12\x13\n" +
	"\x0fITEM_TYPE_EMPTY\x10\x00\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x01\x12\x19\n" +
	"\x15ITEM_TYPE_CREDENTIALS\x10\x02\x12\x12\n" +
	"\x0eITEM_TYPE_TEXT\x10\x03\x12\x14\n" +
	"\x10ITEM_TYPE_BINARY\x10\x04\x12\x12\n" +
	"\x0eITEM_TYPE_CARD\x10\x052\xda\x02\n" +
	"\x0fItemsController\x128\n" +
	"\aAddItem\x12\x15.items.AddItemRequest\x1a\x16.items.AddItemResponse\x12;\n" +
	"\bEditItem\x12\x16.items.EditItemRequest\x1a\x17.items.EditItemResponse\x12A\n" +
	"\n" +
	"DeleteItem\x12\x18.items.DeleteItemRequest\x1a\x19.items.DeleteItemResponse\x12G\n" +
	"\fGetUserItems\x12\x1a.items.GetUserItemsRequest\x1a\x1b.items.GetUserItemsResponse\x12D\n" +
	"\vTypesCounts\x12\x19.items.TypesCountsRequest\x1a\x1a.items.TypesCountsResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_internal_protos_items_items_proto_rawDescOnce sync.Once
	file_internal_protos_items_items_proto_rawDescData []byte
)

func file_internal_protos_items_items_proto_rawDescGZIP() []byte {
	file_internal_protos_items_items_proto_rawDescOnce.Do(func() {
		file_internal_protos_items_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_items_items_proto_rawDesc), len(file_internal_protos_items_items_proto_rawDesc)))
	})
	return file_internal_protos_items_items_proto_rawDescData
}

var file_internal_protos_items_items_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protos_items_items_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_protos_items_items_proto_goTypes = []any{
	(ItemType)(0),                 // 0: items.ItemType
	(*EncryptedItem)(nil),         // 1: items.EncryptedItem
	(*EncryptedData)(nil),         // 2: items.EncryptedData
	(*AddItemRequest)(nil),        // 3: items.AddItemRequest
	(*AddItemResponse)(nil),       // 4: items.AddItemResponse
	(*GetUserItemsRequest)(nil),   // 5: items.GetUserItemsRequest
	(*GetUserItemsResponse)(nil),  // 6: items.GetUserItemsResponse
	(*EditItemRequest)(nil),       // 7: items.EditItemRequest
	(*EditItemResponse)(nil),      // 8: items.EditItemResponse
	(*DeleteItemRequest)(nil),     // 9: items.DeleteItemRequest
	(*DeleteItemResponse)(nil),    // 10: items.DeleteItemResponse
	(*TypesCountsRequest)(nil),    // 11: items.TypesCountsRequest
	(*TypesCountsResponse)(nil),   // 12: items.TypesCountsResponse
	nil,                           // 13: items.EncryptedItem.MetaEntry
	nil,                           // 14: items.TypesCountsResponse.TypesEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_internal_protos_items_items_proto_depIdxs = []int32{
	0,  // 0: items.EncryptedItem.type:type_name -> items.ItemType
	2,  // 1: items.EncryptedItem.encrypted_data:type_name -> items.EncryptedData
	13, // 2: items.EncryptedItem.meta:type_name -> items.EncryptedItem.MetaEntry
	15, // 3: items.EncryptedItem.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: items.EncryptedItem.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: items.AddItemRequest.item:type_name -> items.EncryptedItem
	0,  // 6: items.GetUserItemsRequest.type:type_name -> items.ItemType
	1,  // 7: items.GetUserItemsResponse.items:type_name -> items.EncryptedItem
	1,  // 8: items.EditItemRequest.item:type_name -> items.EncryptedItem
	14, // 9: items.TypesCountsResponse.types:type_name -> items.TypesCountsResponse.TypesEntry
	3,  // 10: items.ItemsController.AddItem:input_type -> items.AddItemRequest
	7,  // 11: items.ItemsController.EditItem:input_type -> items.EditItemRequest
	9,  // 12: items.ItemsController.DeleteItem:input_type -> items.DeleteItemRequest
	5,  // 13: items.ItemsController.GetUserItems:input_type -> items.GetUserItemsRequest
	11, // 14: items.ItemsController.TypesCounts:input_type -> items.TypesCountsRequest
	4,  // 15: items.ItemsController.AddItem:output_type -> items.AddItemResponse
	8,  // 16: items.ItemsController.EditItem:output_type -> items.EditItemResponse
	10, // 17: items.ItemsController.DeleteItem:output_type -> items.DeleteItemResponse
	6,  // 18: items.ItemsController.GetUserItems:output_type -> items.GetUserItemsResponse
	12, // 19: items.ItemsController.TypesCounts:output_type -> items.TypesCountsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_protos_items_items_proto_init() }
func file_internal_protos_items_items_proto_init() {
	if File_internal_protos_items_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_items_items_proto_rawDesc), len(file_internal_protos_items_items_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_items_items_proto_goTypes,
		DependencyIndexes: file_internal_protos_items_items_proto_depIdxs,
		EnumInfos:         file_internal_protos_items_items_proto_enumTypes,
		MessageInfos:      file_internal_protos_items_items_proto_msgTypes,
	}.Build()
	File_internal_protos_items_items_proto = out.File
	file_internal_protos_items_items_proto_goTypes = nil
	file_internal_protos_items_items_proto_depIdxs = nil
}
