apiVersion: v1
kind: Pod
metadata:
  name: agent
spec:
  restartPolicy: Never
  containers:
    - name: agent
      image: gophkeeper-agent:latest
      imagePullPolicy: Never
      env:
        - name: ADDRESS
          value: "gophkeeper-service:80"
      stdin: true
      tty: true
