apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: default
data:
  init.sql: |
    -- Create the database if it doesn't exist
    SELECT 'CREATE DATABASE gophkeeper_db'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'gophkeeper_db')
    \gexec
    
    -- Connect to the database
    \c gophkeeper_db;
    
    -- Create types if they don't exist
    DO
    $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_type') THEN
                CREATE TYPE item_type AS ENUM (
                    'UNSPECIFIED',
                    'CREDENTIALS',
                    'TEXT',
                    'BINARY',
                    'CARD'
                    );
            END IF;
        END
    $$;
    
    -- Create tables if they don't exist
    CREATE TABLE IF NOT EXISTS users
    (
        login    VARCHAR(255) PRIMARY KEY,
        password BYTEA NOT NULL
    );
    
    CREATE TABLE IF NOT EXISTS items
    (
        id                UUID PRIMARY KEY         DEFAULT gen_random_uuid(),
        user_login        VARCHAR(255) NOT NULL REFERENCES users (login) ON DELETE CASCADE,
        name              VARCHAR(255) NOT NULL,
        type              item_type    NOT NULL,
        encrypted_content TEXT         NOT NULL,
        nonce             TEXT         NOT NULL,
        meta              JSONB,
        created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    -- Create indexes
    CREATE INDEX IF NOT EXISTS idx_items_user_login ON items (user_login);
    CREATE INDEX IF NOT EXISTS idx_items_type ON items (type);
    CREATE INDEX IF NOT EXISTS idx_items_created_at ON items (created_at);
