apiVersion: v1
kind: Secret
metadata:
  name: gophkeeper-secrets
  namespace: default
type: Opaque
stringData:
  AUTH_SECRET_KEY: "your-super-secret-jwt-key-for-development"
  DATABASE_URI: "postgres://dmitrij:Antirise1!@postgres:5432/gophkeeper_db?sslmode=disable"
