// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protos/users/users.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_protos_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_protos_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpUserRequest) Reset() {
	*x = SignUpUserRequest{}
	mi := &file_internal_protos_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpUserRequest) ProtoMessage() {}

func (x *SignUpUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpUserRequest.ProtoReflect.Descriptor instead.
func (*SignUpUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SignUpUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpUserResponse) Reset() {
	*x = SignUpUserResponse{}
	mi := &file_internal_protos_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpUserResponse) ProtoMessage() {}

func (x *SignUpUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpUserResponse.ProtoReflect.Descriptor instead.
func (*SignUpUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignUpUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SignInUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInUserRequest) Reset() {
	*x = SignInUserRequest{}
	mi := &file_internal_protos_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInUserRequest) ProtoMessage() {}

func (x *SignInUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInUserRequest.ProtoReflect.Descriptor instead.
func (*SignInUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *SignInUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SignInUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInUserResponse) Reset() {
	*x = SignInUserResponse{}
	mi := &file_internal_protos_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInUserResponse) ProtoMessage() {}

func (x *SignInUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInUserResponse.ProtoReflect.Descriptor instead.
func (*SignInUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *SignInUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignInUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_protos_users_users_proto protoreflect.FileDescriptor

const file_internal_protos_users_users_proto_rawDesc = "" +
	"\n" +
	"!internal/protos/users/users.proto\x12\x05users\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"4\n" +
	"\x11SignUpUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"@\n" +
	"\x12SignUpUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x11SignInUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"@\n" +
	"\x12SignInUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x96\x01\n" +
	"\x0eUserController\x12A\n" +
	"\n" +
	"SignUpUser\x12\x18.users.SignUpUserRequest\x1a\x19.users.SignUpUserResponse\x12A\n" +
	"\n" +
	"SignInUser\x12\x18.users.SignInUserRequest\x1a\x19.users.SignInUserResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_internal_protos_users_users_proto_rawDescOnce sync.Once
	file_internal_protos_users_users_proto_rawDescData []byte
)

func file_internal_protos_users_users_proto_rawDescGZIP() []byte {
	file_internal_protos_users_users_proto_rawDescOnce.Do(func() {
		file_internal_protos_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_users_users_proto_rawDesc), len(file_internal_protos_users_users_proto_rawDesc)))
	})
	return file_internal_protos_users_users_proto_rawDescData
}

var file_internal_protos_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protos_users_users_proto_goTypes = []any{
	(*User)(nil),               // 0: users.User
	(*SignUpUserRequest)(nil),  // 1: users.SignUpUserRequest
	(*SignUpUserResponse)(nil), // 2: users.SignUpUserResponse
	(*SignInUserRequest)(nil),  // 3: users.SignInUserRequest
	(*SignInUserResponse)(nil), // 4: users.SignInUserResponse
}
var file_internal_protos_users_users_proto_depIdxs = []int32{
	0, // 0: users.SignUpUserRequest.user:type_name -> users.User
	0, // 1: users.SignInUserRequest.user:type_name -> users.User
	1, // 2: users.UserController.SignUpUser:input_type -> users.SignUpUserRequest
	3, // 3: users.UserController.SignInUser:input_type -> users.SignInUserRequest
	2, // 4: users.UserController.SignUpUser:output_type -> users.SignUpUserResponse
	4, // 5: users.UserController.SignInUser:output_type -> users.SignInUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protos_users_users_proto_init() }
func file_internal_protos_users_users_proto_init() {
	if File_internal_protos_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_users_users_proto_rawDesc), len(file_internal_protos_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_users_users_proto_goTypes,
		DependencyIndexes: file_internal_protos_users_users_proto_depIdxs,
		MessageInfos:      file_internal_protos_users_users_proto_msgTypes,
	}.Build()
	File_internal_protos_users_users_proto = out.File
	file_internal_protos_users_users_proto_goTypes = nil
	file_internal_protos_users_users_proto_depIdxs = nil
}
