// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protos/crypto/crypto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicKeyPEMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyPEMRequest) Reset() {
	*x = GetPublicKeyPEMRequest{}
	mi := &file_internal_protos_crypto_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyPEMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyPEMRequest) ProtoMessage() {}

func (x *GetPublicKeyPEMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_crypto_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyPEMRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyPEMRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_crypto_crypto_proto_rawDescGZIP(), []int{0}
}

type GetPublicKeyPEMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyPem  string                 `protobuf:"bytes,1,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyPEMResponse) Reset() {
	*x = GetPublicKeyPEMResponse{}
	mi := &file_internal_protos_crypto_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyPEMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyPEMResponse) ProtoMessage() {}

func (x *GetPublicKeyPEMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_crypto_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyPEMResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyPEMResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_crypto_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicKeyPEMResponse) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

var File_internal_protos_crypto_crypto_proto protoreflect.FileDescriptor

const file_internal_protos_crypto_crypto_proto_rawDesc = "" +
	"\n" +
	"#internal/protos/crypto/crypto.proto\x12\x06crypto\"\x18\n" +
	"\x16GetPublicKeyPEMRequest\"?\n" +
	"\x17GetPublicKeyPEMResponse\x12$\n" +
	"\x0epublic_key_pem\x18\x01 \x01(\tR\fpublicKeyPem2f\n" +
	"\x10CryptoController\x12R\n" +
	"\x0fGetPublicKeyPEM\x12\x1e.crypto.GetPublicKeyPEMRequest\x1a\x1f.crypto.GetPublicKeyPEMResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_internal_protos_crypto_crypto_proto_rawDescOnce sync.Once
	file_internal_protos_crypto_crypto_proto_rawDescData []byte
)

func file_internal_protos_crypto_crypto_proto_rawDescGZIP() []byte {
	file_internal_protos_crypto_crypto_proto_rawDescOnce.Do(func() {
		file_internal_protos_crypto_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_crypto_crypto_proto_rawDesc), len(file_internal_protos_crypto_crypto_proto_rawDesc)))
	})
	return file_internal_protos_crypto_crypto_proto_rawDescData
}

var file_internal_protos_crypto_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protos_crypto_crypto_proto_goTypes = []any{
	(*GetPublicKeyPEMRequest)(nil),  // 0: crypto.GetPublicKeyPEMRequest
	(*GetPublicKeyPEMResponse)(nil), // 1: crypto.GetPublicKeyPEMResponse
}
var file_internal_protos_crypto_crypto_proto_depIdxs = []int32{
	0, // 0: crypto.CryptoController.GetPublicKeyPEM:input_type -> crypto.GetPublicKeyPEMRequest
	1, // 1: crypto.CryptoController.GetPublicKeyPEM:output_type -> crypto.GetPublicKeyPEMResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protos_crypto_crypto_proto_init() }
func file_internal_protos_crypto_crypto_proto_init() {
	if File_internal_protos_crypto_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_crypto_crypto_proto_rawDesc), len(file_internal_protos_crypto_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_crypto_crypto_proto_goTypes,
		DependencyIndexes: file_internal_protos_crypto_crypto_proto_depIdxs,
		MessageInfos:      file_internal_protos_crypto_crypto_proto_msgTypes,
	}.Build()
	File_internal_protos_crypto_crypto_proto = out.File
	file_internal_protos_crypto_crypto_proto_goTypes = nil
	file_internal_protos_crypto_crypto_proto_depIdxs = nil
}
