// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/protos/crypto/crypto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoController_GetPublicKeyPEM_FullMethodName = "/crypto.CryptoController/GetPublicKeyPEM"
)

// CryptoControllerClient is the client API for CryptoController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoControllerClient interface {
	GetPublicKeyPEM(ctx context.Context, in *GetPublicKeyPEMRequest, opts ...grpc.CallOption) (*GetPublicKeyPEMResponse, error)
}

type cryptoControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoControllerClient(cc grpc.ClientConnInterface) CryptoControllerClient {
	return &cryptoControllerClient{cc}
}

func (c *cryptoControllerClient) GetPublicKeyPEM(ctx context.Context, in *GetPublicKeyPEMRequest, opts ...grpc.CallOption) (*GetPublicKeyPEMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyPEMResponse)
	err := c.cc.Invoke(ctx, CryptoController_GetPublicKeyPEM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoControllerServer is the server API for CryptoController service.
// All implementations must embed UnimplementedCryptoControllerServer
// for forward compatibility.
type CryptoControllerServer interface {
	GetPublicKeyPEM(context.Context, *GetPublicKeyPEMRequest) (*GetPublicKeyPEMResponse, error)
	mustEmbedUnimplementedCryptoControllerServer()
}

// UnimplementedCryptoControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoControllerServer struct{}

func (UnimplementedCryptoControllerServer) GetPublicKeyPEM(context.Context, *GetPublicKeyPEMRequest) (*GetPublicKeyPEMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKeyPEM not implemented")
}
func (UnimplementedCryptoControllerServer) mustEmbedUnimplementedCryptoControllerServer() {}
func (UnimplementedCryptoControllerServer) testEmbeddedByValue()                          {}

// UnsafeCryptoControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoControllerServer will
// result in compilation errors.
type UnsafeCryptoControllerServer interface {
	mustEmbedUnimplementedCryptoControllerServer()
}

func RegisterCryptoControllerServer(s grpc.ServiceRegistrar, srv CryptoControllerServer) {
	// If the following call pancis, it indicates UnimplementedCryptoControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoController_ServiceDesc, srv)
}

func _CryptoController_GetPublicKeyPEM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyPEMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoControllerServer).GetPublicKeyPEM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoController_GetPublicKeyPEM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoControllerServer).GetPublicKeyPEM(ctx, req.(*GetPublicKeyPEMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoController_ServiceDesc is the grpc.ServiceDesc for CryptoController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.CryptoController",
	HandlerType: (*CryptoControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKeyPEM",
			Handler:    _CryptoController_GetPublicKeyPEM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/crypto/crypto.proto",
}
